package ldsocache

import (
	"testing"
	"github.com/stretchr/testify/require"
)

func Test_LoadCacheFile(t *testing.T) {
	cacheFile, err := LoadCacheFile("testdata/ld.so.cache")
	require.NoError(t, err)
	require.Equalf(t, uint32(65), cacheFile.Header.NumLibs, "there should be 65 libraries in this cache file")
	require.Equalf(t, uint32(1421), cacheFile.Header.StrTableSize, "the string table should be 1421 bytes long")
	require.Equalf(t, 1, len(cacheFile.Extensions), "there must be 1 extension")

	ext := cacheFile.Extensions[0]
	require.Equalf(t, uint32(0), ext.Header.Tag, "extension data must be tag 0 (generator)")
	require.Equalf(t, []byte("ldconfig (GNU libc) stable release version 2.36"), ext.Data, "must be generated by glibc 2.36")
}

func Test_WriteCacheFile(t *testing.T) {
	cacheFile, err := LoadCacheFile("testdata/ld.so.cache")
	require.NoError(t, err)

	err = cacheFile.Write("testdata/ld.so.cache-new")
	require.NoError(t, err)
}

func do_compare(t *testing.T, a string, b string, expected int) {
	cmp, err := soname_cmp(SoVer(a), SoVer(b))
	require.NoError(t, err)
	require.Equal(t, expected, cmp)
}

func Test_SoVer_Compare_Equal_Int(t *testing.T) {
	do_compare(t, "1.0", "1.0", 0)
}

func Test_SoVer_Compare_Greater_Int(t *testing.T) {
	do_compare(t, "1.0", "1.0.1", -1)
	do_compare(t, "1.0", "1.1", -1)
}

func Test_SoVer_Compare_Lesser_Int(t *testing.T) {
	do_compare(t, "1.0.1", "1.0", 1)
	do_compare(t, "1.1", "1.0", 1)
}

func Test_SoVer_Compare_Equal_String(t *testing.T) {
	do_compare(t, "1.foo1", "1.foo1", 0)
}

func Test_SoVer_Compare_Greater_String(t *testing.T) {
	do_compare(t, "1.1", "1.1.foo", -1)
	do_compare(t, "1.1", "1.foo1", -1)
	do_compare(t, "1.1foo1", "1.foo2", -1)
}

func Test_SoVer_Compare_Lesser_String(t *testing.T) {
	do_compare(t, "1.1.foo", "1.1", 1)
	do_compare(t, "1.foo1", "1.1", 1)
	do_compare(t, "1.foo2", "1.1foo1", 1)
}

func Test_GenerateCacheFile(t *testing.T) {
	cacheFile, err := BuildCacheFileForConfig("/etc/ld.so.conf")
	require.NoError(t, err)

	err = cacheFile.Write("testdata/ld.so.cache-new")
	require.NoError(t, err)
}
